version: '3.5'
services:
    db:
        image: mysql:5.7
        container_name: nodedb
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mysql

        ports:
          - 3306:3306
        volumes:
          - mysql:/var/lib/mysql

volumes:
    mysql:


