version: '3'
services:
    watchtower:
      image: containrrr/watchtower
      volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
      command: --interval 30 --cleanup --debug --trace --include-restarting himmussel/odontomaster
      restart: always
    app:
      build: .
      image: himmussel/odontomaster
      container_name: odontomaster
      restart: always
      networks:
        - backend
      environment:
        DB_DIALECT: ${DB_CONNECTION}
        DB_DATABASE: ${DB_DATABASE}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USERNAME: ${DB_USERNAME}
        DB_HOST: nodedb
        NODE_ENV: production

      ports:
        - 8100:80
      volumes:
        - "./.docker/nginx.conf:/etc/nginx/nginx.conf"
    db:
        image: mysql:5.7
        container_name: nodedb
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mysql
        networks:
          - backend
        ports:
          - 3306:3306
        volumes:
          - mysql:/var/lib/mysql
networks:
    backend:
        driver: bridge
volumes:
    mysql:


