version: '3'
services:
    frontend:
      build: .
      image: himmussel/larodon-frontend
      container_name: larodon-frontend
      restart: always
      networks:
        - backend
      environment:
        PM2_PUBLIC_KEY: ${PM2_PUBLIC_KEY}
        PM2_SECRET_KEY: ${PM2_SECRET_KEY}
        DB_DATABASE: ${DB_DATABASE}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USERNAME: ${DB_USERNAME}
        DB_HOST: laraveldb
      ports:
        - 81:80
      volumes: 
        - "./.docker/nginx.conf:/etc/nginx/nginx.conf"
    db:
        image: mysql:5.7
        container_name: laraveldb
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mysql
        networks:
          - backend
        ports:
          - 3306:3306
        volumes:
          - ./.docker/data:/var/lib/mysql
networks:
    backend:
        driver: bridge


