name: ci

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: DockerCheckout
        uses: actions/checkout@v2

      - name: Create .env for app
        uses: weyheyhey/create-dotenv-action@v1
        with:
          wildecard: "^"
          filename: "app/.env"
        env:
          ^VUE_APP_BUILD: ${{ github.run_id }}
          ^VUE_APP_BASE_API: /api/
          
      - name: Create .env for api
        uses: weyheyhey/create-dotenv-action@v1
        with:
          wildecard: "^"
          filename: "api/.env"
        env:
          ^JWT_KEY: ${{ secrets.JWT_SECRET }}
          ^DEFAULT_PASSWORD: 123
          ^GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ^UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: himmussel/odontomaster:latest
