name: ci

on:
  push:
    branches:
      - 'develop'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: DockerCheckout
        uses: actions/checkout@v2

      -
        name: create env files for app
        run: |
            printf "\nVUE_APP_BUILD=%s\n" ${GITHUB_RUN_ID} >> app/.env-production
            printf "VUE_APP_BASE_API=/api/\n" >> app/.env-production
            printf "JWT_KEY=%s\n" "${{ secrets.JWT_SECRET }}" >> api/.env
            printf "DEFAULT_PASSWORD=123123\n" >> api/.env
            printf "GITHUB_TOKEN=%s\n" "${{ secrets.TOKEN }}" >> api/.env

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: himmussel/odontomaster:development